import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/src/lib/utils";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body className={cn("grainy min-h-screen font-sans antialiased", inter.className)}>{children}</body>
    </html>
  );
}
